### ISSUE TITLE
Create an article in the quality hub for Release a reusable module pattern

### ISSUE THREAD

**Issue by itualami** [rosin-project/quality-hub#3]
@ipa-jfh Create an article in the quality hub for Release a reusable module pattern

**Comment by Chamango90** [comment]
As discussed in the last meeting we should not try to recreate content but link and improve existing one.
For now, I linked the relevant external tutorials and highlighted that they are external. I started with three tutorials:
1. Index your package 
1. Releasing a package for the first time
1. Releasing a new version of a package
