### ISSUE TITLE
Continuous integration with the public infrastructure pattern

### ISSUE THREAD

**Issue by itualami** [rosin-project/quality-hub#4]
@ipa-jfh Liaise with Nicholas to create an article for Continuous integration with the public infrastructure in the quality hub http://wiki.ros.org/Quality

**Comment by Chamango90** [comment]
Hi Nicolas, 
we (see [current issues](https://github.com/rosin-project/quality-hub/issues)) want to review the SW-Q patterns and move the content to the Quality wiki within http://wiki.ros.org/Quality/Tutorials. Do you have access to our pattern-collection? Could you please take over the `Continuous integration with the public infrastructure` topic?

- In the last meeting we decided to focus in particular on the pattern's fields `Context/Problem` and `Solution`
- We will have the next meeting on 26.03.

@itualami can you please assign @nlimpert to this issue?

**Comment by nlimpert** [comment]
Hi Jonathan,

I don't think I'm aware of the pattern-collection.
Do you have a protocol from the last meeting?

Depending on what was discussed in the last meeting I would do the following:
 - Context/Problem: Continuous integration with Travis CI / ROS buildfarm vs. a custom set-up continuous integration infrastructure. Why continuous integration in general? (automated testing / clean deployment)
 - Solution: Tutorial on Travis CI / (other aspects to be discussed)

I was thinking on involving the tool "bloom (http://wiki.ros.org/bloom)" but there are obviously quite a lot tutorials available.

What do you think? Is there a better aspect to be covered?
Do you plan to be done with the articles by 26.03.?

**Comment by Chamango90** [comment]
> Do you have a protocol from the last meeting?

@itualami could you sent it to Nicolas?
@ipa-jfh What do you mean by "protocol"?

> I don't think I'm aware of the pattern-collection.
> Do you plan to be done with the articles by 26.03.?

Hi Niklas,
sorry I should have posted the link to the patterns right away. Here it is
https://rosin-project.github.io/quality-hub/
The content has already been created at `Pattern 3: Continuous integration with the public infrastructure`. Thus, you should not need to recreate content. We want however to simplify the structure: remove the sub-points and focus on `Context/Problem` and `Solution`; and finally move it to the wiki-page. Yes, the plan would be to do this before the 26.03. Do you find time for it?

> Depending on what was discussed in the last meeting I would do the following:
> 
> Context/Problem: Continuous integration with Travis CI / ROS buildfarm vs. a custom set-up continuous integration infrastructure. Why continuous integration in general? (automated testing / clean deployment)
>     Solution: Tutorial on Travis CI / (other aspects to be discussed)
> What do you think? Is there a better aspect to be covered?
@nlimpert I can send you a copy of the pattern Continuous Integration with public infrastructure
Be aware that we have also patterns about `Pattern 6: Release a reusable module`, `Continuous integration with the private infrastructure` , ...

**Comment by nlimpert** [comment]
@ipa-jfh Thanks for the detailed notice.

With "protocol" I meant he meeting minutes - sorry!

I started to create the article and it's available in the "Continuous Integration" List:
http://wiki.ros.org/Quality/Tutorials

The content is the same as the pattern in the quality hub.

Is the current state of this article what was intented?
I am particularly unsure on how to remove sub points - do you mean to merge the "Forces" section to the problem section?

And there are links missing to the "related patterns" yet. I guess this would be rather called "Related Tutorials" with links to the according tutorials. Do you agree?

I did not set up any Tutorial Level yet. I was thinking of "intermediate" - what do you think?

**Comment by Chamango90** [comment]
Thank you Niklas! 

In my opinion We should delete the "forces" for now. 

4.4 and probably 4.3 seems to be sub-point of 4.2. ?

> And there are links missing to the "related patterns" yet. I guess this would be rather called "Related Tutorials" with links to the according tutorials. Do you agree?

I agree on this.

To set up the CI for ROS buildfarm or industrial-ci would not be that difficuld. So I am considering one of the first 2 levels.

**Comment by nlimpert** [comment]
Hi Jon,

thank you for the input! I updated the article according to your suggestions.

I don't think that I got an invitation for the next meeting tomorrow. Could you tell me when and where you are going to meet? Is it a Hangouts group?

**Comment by itualami** [comment]
Hi Niklas, @nlimpert 
I send the invite to next meeting to this email nicolas.limpert@alumni.fh-aachen.de if this is not the right email, please send me your email.

**Comment by nlimpert** [comment]
Hi Adam,
thank you - my bad. I found the invitation.
My employee's mail address is limpert@fh-aachen.de.
