### ISSUE TITLE
Create an article for Regression test (Unit test) pattern

### ISSUE THREAD

**Issue by itualami** [rosin-project/quality-hub#5]
@wasowski Create an article for Regression test (Unit test) pattern in the quality hub http://wiki.ros.org/Quality

**Comment by wasowski** [comment]
For the record: I decided to try to use the existing http://wiki.ros.org/UnitTesting and integrate what is in our pattern into it. Let's see how it goes...

**Comment by wasowski** [comment]
Done! http://wiki.ros.org/UnitTesting (and linked from the Quality Hub)
