### ISSUE TITLE
Create an article for Integrating tests in the build (catkin) pattern 

### ISSUE THREAD

**Issue by itualami** [rosin-project/quality-hub#6]
@jontje Create an article for Integrating tests in the build (catkin) pattern in the quality hub http://wiki.ros.org/Quality

**Comment by wasowski** [comment]
Jon, when you work on that please also fix a link to this patter from http://wiki.ros.org/UnitTesting (or talk to me and I will fix it).

**Comment by jontje** [comment]
Done ([http://wiki.ros.org/Quality/Tutorials/Integrate%20tests%20in%20catkin](url)) and a link has also been added to the Quality/Tutorials page.

@wasowski: I have added a link.
